x-app: &app
  labels:
    logging: "promtail"
    logging_jobname: "containerlogs"
  tty: true
  stdin_open: true
  environment: &app-env
    LOG_LEVEL: -1
    REDIS_DSN: redis://redis:6379/0
    KAFKA_BROKERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
    KAFKA_LOG_LEVEL: 0

services:
  gophermart_fake_orders:
    <<: *app
    container_name: gophermart-fake-orders
    image: docker-gophermart-fake-orders
    command:
      ./api
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_development
      ACCRUAL_CREATE_GOODS_URL: http://accruals-service:8080/api/goods
      GRPC_ADDRESS: 0.0.0.0:8050
      HTTP_ADDRESS: 0.0.0.0:8060
    ports:
      - 8060:8060

  gophermart_accrual_adapter-order_created_consumer:
    <<: *app
    container_name: gophermart-accrual_adapter-order_created_consumer
    image:  docker-gophermart_accrual_adapter-order_created_consumer
    command:
      ./order_created_consumer
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_accrual_adapter_development
      KAFKA_ORDER_CREATED_MAX_WAIT_INTERWAL: 250

  gophermart_accrual_adapter-order_created_daemons:
    <<: *app
    container_name: gophermart-accrual_adapter-order_created_daemons
    image: docker-gophermart_accrual_adapter-order_created_daemons
    command:
      ./order_created_daemons
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_accrual_adapter_development
      GOPHERMART_GRPC_ADDRESS: gophermart-fake-orders:8050
      ACCRUAL_HTTP_ADDRESS: http://accruals-service:8080
      DAEMON_WORKERS_COUNT: 5
      DAEMON_POLL_INTERVAL: 100

  gophermart_accrual_adapter-transaction_outbox:
    <<: *app
    container_name: gophermart_accrual_adapter-transaction_outbox
    image: docker-gophermart_accrual_adapter-transaction_outbox
    command:
      ./transaction_outbox
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_accrual_adapter_development
      DAEMON_DAEMON_WORKERS_COUNT: 5
      ACCRUALS_OUTBOX_POLL_INTERVAL: 10

  gophermart_billing-sync_commands:
    <<: *app
    container_name: gophermart-billing_sync_commands
    image: docker-billing_sync_commands
    command:
      ./billing_sync_commands
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_billing_development
      ORDERS_SERVER_HTTP_ADDRESS: 0.0.0.0:8010
      AccountingServerHTTPAddress: 0.0.0.0:8020
      DAEMON_ACCRUALS_WORKERS_COUNT: 5

  gophermart_billing_accruals_consumer:
    <<: *app
    container_name: gophermart_billing_accruals_consumer
    image: docker-billing_consumer
    command:
      ./billing_accruals_consumer
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_billing_development
      DAEMON_ACCRUALS_WORKERS_COUNT: 5
      KAFKA_ACCRUALS_MAX_WAIT_INTERVAL: 500
  gophermart_portal-api:
    <<: *app
    container_name: gophermart_portal-api
    image: docker-gophermart-portal-api
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_api_development
      HTTP_ADDRESS: 0.0.0.0:8000
      BILLING_ORDERS_ADDRESS: gophermart-billing_sync_commands:8010
      BILLING_ACCOUNTING_ADDRESS: gophermart-billing_sync_commands:8020
      QUERY_ORDERS_ADDRESS: gophermart_query-grpc_server:8030
      QUERY_ACCOUNTING_ADDRESS: gophermart_query-grpc_server:8040
      IAM_TOKEN_TTL: 600
    ports:
      - 8000:8000

  gophermart_query-order_created_consumer:
    <<: *app
    image: docker-query_order_created_consumer
    container_name: gophermart_query-order_created_consumer
    command:
      ./order_created_consumer
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_query_development
      KAFKA_ORDER_CREATED_MAX_WAIT_INTERWAL: 250

  gophermart_query-order_updated_consumer:
    <<: *app
    image: docker-query_order_updated_consumer
    container_name: gophermart_query-order_updated_consumer
    command:
      ./order_updated_consumer
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_query_development
      ORDERS_SERVER_HTTP_ADDRESS: 0.0.0.0:8030
      ACCOUNTING_SERVER_HTTP_ADDRESS: 0.0.0.0:8040
      KAFKA_ORDER_UPDATED_MAX_WAIT_INTERWAL: 250

  gophermart_query-transaction_processed_consumer:
    <<: *app
    image: docker-query_transaction_processed_consumer
    container_name: gophermart_query-transaction_processed_consumer
    command:
      ./transaction_processed_consumer
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_query_development
      DAEMON_WORKERS_COUNT: 1
      KAFKA_TRANSACTION_PROCESSED_MAX_WAIT_INTERWAL: 500

  gophermart_query-grpc_server:
    <<: *app
    image: docker-grpc_server
    container_name: gophermart_query-grpc_server
    command:
      ./grpc_server
    environment:
      <<: *app-env
      DATABASE_DSN: postgres://postgres:secret@db:5432/gophermart_query_development
      ORDERS_SERVER_HTTP_ADDRESS: 0.0.0.0:8030
      ACCOUNTING_SERVER_HTTP_ADDRESS: 0.0.0.0:8040

networks:
  default:
    name: gophermart-network