global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'kafka-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]

  - job_name: 'kafka'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'kafka-1:5556', 'kafka-2:5556', 'kafka-3:5556' ]